### Identify different languages from text

#### Import necessary packages

In [2]:
import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('C:\\Users\\DELL\\Downloads\\Language_recognization.csv')
df.head(5)

Text Language
0   Nature, in the broadest sense, is the natural...  English
1  "Nature" can refer to the phenomena of the phy...  English
2  The study of nature is a large, if not the onl...  English
3  Although humans are part of nature, human acti...  English
4  [1] The word nature is borrowed from the Old F...  English

In [4]:
df['Language'].value_counts()

English       1385
French        1014
Spanish        819
Portugeese     739
Italian        698
Russian        692
Sweedish       676
Malayalam      594
Dutch          546
Arabic         536
Turkish        474
German         470
Tamil          469
Danish         428
Kannada        369
Greek          365
Hindi           63
Name: Language, dtype: int64

In [7]:
X = df['Text']
y = df['Language']

In [8]:
# basic function for the preprocessing 
X_list=[]
for text in X:
    # removing the symbols and numbers
    text = re.sub(r'[!@#$(),n"%^*?:;~`0-9]', ' ', text)
    text = re.sub(r'[[]]', ' ', text)
    # converting the text to lower case
    text = text.lower()
    # appending to data_list
    X_list.append(text)

C:\Users\DELL\AppData\Local\Temp\ipykernel_15156\2094671962.py:6: FutureWarning: Possible nested set at position 1
  text = re.sub(r'[[]]', ' ', text)


In [9]:
X_list[:5]

[' nature  i  the broadest se se  is the  atural  physical  material world or u iverse.',
 ' nature  ca  refer to the phe ome a of the physical world  a d also to life i  ge eral.',
 'the study of  ature is a large  if  ot the o ly  part of scie ce.',
 'although huma s are part of  ature  huma  activity is ofte  u derstood as a separate category from other  atural phe ome a.',
 '[ ] the word  ature is borrowed from the old fre ch  ature a d is derived from the lati  word  atura  or  esse tial qualities  i  ate dispositio    a d i  a cie t times  literally mea t  birth .']

In [71]:
X

0         Nature, in the broadest sense, is the natural...
1        "Nature" can refer to the phenomena of the phy...
2        The study of nature is a large, if not the onl...
3        Although humans are part of nature, human acti...
4        [1] The word nature is borrowed from the Old F...
                               ...                        
10332    ನಿಮ್ಮ ತಪ್ಪು ಏನು ಬಂದಿದೆಯೆಂದರೆ ಆ ದಿನದಿಂದ ನಿಮಗೆ ಒ...
10333    ನಾರ್ಸಿಸಾ ತಾನು ಮೊದಲಿಗೆ ಹೆಣಗಾಡುತ್ತಿದ್ದ ಮಾರ್ಗಗಳನ್...
10334    ಹೇಗೆ ' ನಾರ್ಸಿಸಿಸಮ್ ಈಗ ಮರಿಯನ್ ಅವರಿಗೆ ಸಂಭವಿಸಿದ ಎ...
10335    ಅವಳು ಈಗ ಹೆಚ್ಚು ಚಿನ್ನದ ಬ್ರೆಡ್ ಬಯಸುವುದಿಲ್ಲ ಎಂದು ...
10336    ಟೆರ್ರಿ ನೀವು ನಿಜವಾಗಿಯೂ ಆ ದೇವದೂತನಂತೆ ಸ್ವಲ್ಪ ಕಾಣು...
Name: Text, Length: 10337, dtype: object

In [10]:
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer

cv = CountVectorizer()
tv = TfidfVectorizer()


In [11]:
X_tv = tv.fit_transform(X_list).toarray()
X_tv.shape

(10337, 34937)

In [13]:
df100 = pd.DataFrame(X_tv,columns=tv.get_feature_names_out())
df100

aa  aaktslak  aal  aam  aamd  aamwoord  aar  aardappele  aardig  \
0      0.0       0.0  0.0  0.0   0.0       0.0  0.0         0.0     0.0   
1      0.0       0.0  0.0  0.0   0.0       0.0  0.0         0.0     0.0   
2      0.0       0.0  0.0  0.0   0.0       0.0  0.0         0.0     0.0   
3      0.0       0.0  0.0  0.0   0.0       0.0  0.0         0.0     0.0   
4      0.0       0.0  0.0  0.0   0.0       0.0  0.0         0.0     0.0   
...    ...       ...  ...  ...   ...       ...  ...         ...     ...   
10332  0.0       0.0  0.0  0.0   0.0       0.0  0.0         0.0     0.0   
10333  0.0       0.0  0.0  0.0   0.0       0.0  0.0         0.0     0.0   
10334  0.0       0.0  0.0  0.0   0.0       0.0  0.0         0.0     0.0   
10335  0.0       0.0  0.0  0.0   0.0       0.0  0.0         0.0     0.0   
10336  0.0       0.0  0.0  0.0   0.0       0.0  0.0         0.0     0.0   

       aardiger  ...  ർവഹ   ർസ   ൽക   ൽഗ   ൽത   ൽപ  ൽവർ   ൾക   ൾപ   ൾമ  
0           0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1           0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2           0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
3           0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4           0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
...         ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  
10332       0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
10333       0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
10334       0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
10335       0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
10336       0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[10337 rows x 34937 columns]

#### Encoding the target variable

In [14]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y = le.fit_transform(y)
print(y)

[3 3 3 ... 9 9 9]


In [17]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X_tv,y,test_size=0.2)

In [18]:
from sklearn.naive_bayes import MultinomialNB

nb = MultinomialNB()
nb.fit(X_train,y_train)

MultinomialNB()

In [19]:
y_pred = nb.predict(X_test)

In [20]:
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix

accuracy = accuracy_score(y_test,y_pred)
accuracy

0.9434235976789168

In [21]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      0.92      0.96       110
           1       1.00      0.85      0.92       101
           2       0.99      0.90      0.94       105
           3       0.75      1.00      0.85       280
           4       0.95      0.98      0.97       193
           5       1.00      0.95      0.98       104
           6       1.00      0.92      0.96        71
           7       1.00      0.89      0.94         9
           8       0.99      0.95      0.97       144
           9       1.00      0.91      0.95        68
          10       1.00      0.98      0.99       115
          11       0.99      0.95      0.97       147
          12       1.00      0.90      0.95       144
          13       0.97      0.98      0.97       148
          14       0.97      0.97      0.97       147
          15       1.00      0.97      0.98        87
          16       1.00      0.79      0.88        95

    accuracy              

In [22]:
print(confusion_matrix(y_test,y_pred))

[[101   0   0   9   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0  86   0   8   3   0   0   0   0   0   0   0   0   0   4   0   0]
 [  0   0  94  10   1   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0 279   0   0   0   0   1   0   0   0   0   0   0   0   0]
 [  0   0   0   3 190   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   5   0  99   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   6   0   0  65   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   1   0   0   0   8   0   0   0   0   0   0   0   0   0]
 [  0   0   0   4   1   0   0   0 137   0   0   0   0   2   0   0   0]
 [  0   0   0   6   0   0   0   0   0  62   0   0   0   0   0   0   0]
 [  0   0   0   2   0   0   0   0   0   0 113   0   0   0   0   0   0]
 [  0   0   0   4   0   0   0   0   0   0   0 140   0   3   0   0   0]
 [  0   0   0  13   1   0   0   0   0   0   0   0 130   0   0   0   0]
 [  0   0   0   2   0   0   0   0   0   0   0   1   0 145   0   0   0]
 [  0 

In [24]:
def predict(text):
    X = tv.transform([text]).toarray()
    output = nb.predict(X)
    output_trans = le.inverse_transform(output)
    return output_trans[0]

In [25]:
predict('hello')

'English'

In [26]:
import pickle
pickle.dump(tv,open('vectorizer.pkl','wb'))
pickle.dump(nb,open('model.pkl','wb'))
pickle.dump(le,open('label_encoding.pkl','wb'))